name: Publish Nuget Package

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - production

jobs:
  publish_nuget:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x

    - name: Update version files
      env:
        GITHUB_RUN_NUMBER: $${{env.GITHUB_RUN_NUMBER}}
      run: |
        ls
        sed -i -e "s/1.0.0/1.0.$GITHUB_RUN_NUMBER/g" ./**/*.csproj

    - name: Package the project
      run: dotnet pack --configuration Release --verbosity normal

    - name: Publish the project
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        GITHUB_RUN_NUMBER: $${{env.GITHUB_RUN_NUMBER}}
      run: |
        dotnet nuget push "./HubSpot.NET/bin/Release/HubSpot.NETCORE.1.0.$GITHUB_RUN_NUMBER.nupkg"  --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

