name: Run Tests

# Triggers the workflow on push or pull request events
on: [push]
jobs:
  test_platform:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x.x

    - name: Package the project
      run: dotnet pack ./HubSpot.NETCore.sln --configuration Release --verbosity normal -r  ./test-results --logger "GitHubActions;" --logger "trx;LogFilePath=./TestResults/test_result.trx" --collect:"XPlat Code Coverage" --settings $GITHUB_WORKSPACE/coverlet.runsettings

    - name: Publish the project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push "bin/Release/HubSpot.NETCore.1.0.0.nupkg"  --api-key GITHUB_TOKEN --source "github"

